env:
  IMAGE_ID: $IMAGE_ID
agents:
  queue: mac

steps:
  - label: ":testflight: Build Simplenote iOS for App Store Connect"
    key: testflight_build
    command: |
      .buildkite/commands/checkout-release-branch.sh $RELEASE_VERSION
      .buildkite/commands/release-build.sh
    priority: 1
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - build/results/*.zip
      - build/results/*.ipa

  - label: ":testflight: Upload Simplenote iOS to App Store Connect"
    depends_on: testflight_build
    # This step does not only upload to ASC, but also create a GitHub release.
    # For that, it needs to be on the latest release branch commit, hence the checkout command
    command: |
      .buildkite/commands/checkout-release-branch.sh $RELEASE_VERSION
      .buildkite/commands/release-upload.sh $BETA_RELEASE
    priority: 1
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
    - slack: "#build-and-ship"
